version: '3.0'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: esmbotmin
    restart: unless-stopped
    volumes:
      - ./logs:/home/esmBot/.internal/logs
    env_file:
      - .env